<?PHP
//command_base‚Ì“Ç‚Ýž‚Ý
    include_once "include/Util.php";

//    include_once "./module/Report.inc";
    include_once "./module/reportEx.inc";
//    include_once "./module/zip_match.inc";
//    include_once "./module/sendmail.inc";
//    include_once "./module/feed.inc";
//    include_once "./module/multimail.inc";
//    include_once "./module/Banner.inc";
//    include_once "./module/access.inc";
//    include_once "./module/clip.inc";
//    include_once "./module/s_condition.inc";
//    include_once "./module/sys_mail.inc";
//    include_once "./module/History.inc";
//    include_once "./module/favorites.inc";

//command
//    include_once "./module/command/xxxx.inc";

	include_once './module/cUser.inc';
	include_once './module/secretAdwares.inc';
	include_once './module/accountLock.inc';

    